spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

open:
  api:
    key: ${OPEN_API_KEY}
