spring:
  datasource:
    url: jdbc:h2:mem:test;mode=mysql
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

open:
  api:
    key: ${OPEN_API_KEY}
